### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by Sillium** [trojanc/node-influx-uptimerobot#1]
Nice project, thanks!

Seems to be broken with the new API (https://uptimerobot.com/api). Old API (https://uptimerobot.com/apiv1) was retired. Do you have any plans to adapt to the new API?

**Comment by trojanc** [comment]
Hi thanks for update, I haven't looked at this again for a while.
I looks like they changed the URL again, when I did this a while back v2 was not publicly announced yet and I was using the v2 api which was available at https://api.uptimerobot.com/v2 which it now looks like they moved it? The docs used to be available at https://uptimerobot.com/apiv2 (which is now dead), although the new docs (https://uptimerobot.com/api) still refer to using api.uptimerobot.com/v2 as the endpoind. 

Anyway I'll try and give this a spin the weekend if I have some time and see what's cooking here ;)
In the mean while it should be easy to fix by changing [Line 22](https://github.com/trojanc/node-influx-uptimerobot/blob/master/index.js#L22) if the URL needs to change. Otherwise if they also changed the objects it might require some more work

**Comment by Sillium** [comment]
Thanks for the quick reply! I'll see if the URL change alone does it.

*Update:* URL does not seem to have changed. I can use the following cURL without problems:
```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -d 'api_key=<KEY>&format=json&logs=1' "https://api.uptimerobot.com/v2/getMonitors"
```

**Comment by Sillium** [comment]
FWIW, the error message when using your project is
```
Error: {"error":"unable to parse 'logs,friendlyname=xxx\\ -\\ Shop,id=xxx type=2,reason=\"undefined\",reason_detail=undefined 1511488376000': invalid boolean\nunable to parse 'logs,friendlyname=xxx\\ -\\ Shop,id=xxx type=1,reason=\"undefined\",reason_detail=undefined 1511485358000': invalid boolean\nunable to parse
…
```
I x-ed out the details.

The log lines above the error message look like this:
```
[{"type":2,"time":1496990281000,"reason":"undefined"},{"id":xxx,"friendlyname":"xxx"}]
```

**Comment by trojanc** [comment]
I think I have it sorted now. It was not the api, but just a bug that didn't check for undefined values.

**Comment by Sillium** [comment]
Very nice, it works! Thanks again for this useful tool.

I do have a problem with the time offset in [Line 51](https://github.com/trojanc/node-influx-uptimerobot/blob/master/index.js#L51) and I'll see what I can do about it, maybe in form of a pull request. For now, I just set the offset to 0, which seems to work for me and my timezones in the browser, Grafana and InfluxDB.

**Comment by trojanc** [comment]
Yes that timezone stuff was an issue back then. I've sent a issue to uptime robot back then about the data not sent in the proper timezone, so I then had to do that trick to make it work for me. Maybe they have fixed the API now, and I might be able to remove that now...
